"""add knowledge crawl persistence

Revision ID: 739f78b48808
Revises: b9f41d72a4c8
Create Date: 2026-07-24 14:21:22.147328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app.database import GUID

# revision identifiers, used by Alembic.
revision: str = '739f78b48808'
down_revision: Union[str, None] = 'b9f41d72a4c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_jobs',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('starting_urls', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('crawl_mode', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('configuration', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('requested_by_id', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pages_discovered', sa.Integer(), nullable=False),
    sa.Column('pages_fetched', sa.Integer(), nullable=False),
    sa.Column('product_pages_found', sa.Integer(), nullable=False),
    sa.Column('products_parsed', sa.Integer(), nullable=False),
    sa.Column('products_persisted', sa.Integer(), nullable=False),
    sa.Column('products_failed', sa.Integer(), nullable=False),
    sa.Column('pages_skipped', sa.Integer(), nullable=False),
    sa.Column('current_queue_size', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('consecutive_blocks', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('robots_txt', sa.Text(), nullable=True),
    sa.Column('robots_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('crawler_version', sa.String(length=50), nullable=False),
    sa.CheckConstraint("crawl_mode IN ('single_url', 'multiple_urls', 'category', 'brand_catalogue', 'sitemap', 'sitemap_index', 'full_domain')", name='check_crawl_mode'),
    sa.CheckConstraint("status IN ('queued', 'discovering', 'crawling', 'parsing', 'partially_completed', 'completed', 'paused', 'cancelled', 'blocked', 'failed')", name='check_crawl_status'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_jobs_domain'), 'crawl_jobs', ['domain'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_heartbeat_at'), 'crawl_jobs', ['heartbeat_at'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_status'), 'crawl_jobs', ['status'], unique=False)
    op.create_table('crawl_urls',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('crawl_job_id', GUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('normalized_url', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('parent_url_id', GUID(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('page_type', sa.String(length=50), nullable=True),
    sa.Column('classification_reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('error_reason', sa.Text(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("page_type IN ('product', 'category', 'pagination', 'editorial', 'irrelevant', 'blocked', 'unknown', 'sitemap')", name='check_crawl_url_page_type'),
    sa.CheckConstraint("state IN ('queued', 'fetching', 'visited', 'skipped', 'failed', 'completed')", name='check_crawl_url_state'),
    sa.ForeignKeyConstraint(['crawl_job_id'], ['crawl_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_url_id'], ['crawl_urls.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crawl_frontier_claim', 'crawl_urls', ['crawl_job_id', 'state', 'priority', 'next_attempt_at'], unique=False)
    op.create_index(op.f('ix_crawl_urls_crawl_job_id'), 'crawl_urls', ['crawl_job_id'], unique=False)
    op.create_index(op.f('ix_crawl_urls_next_attempt_at'), 'crawl_urls', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_crawl_urls_state'), 'crawl_urls', ['state'], unique=False)
    op.create_index('uq_crawl_job_normalized_url', 'crawl_urls', ['crawl_job_id', 'normalized_url'], unique=True)
    op.create_table('raw_page_observations',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('crawl_job_id', GUID(), nullable=False),
    sa.Column('crawl_url_id', GUID(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('final_url', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('response_headers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('structured_data_hash', sa.String(length=64), nullable=True),
    sa.Column('etag', sa.Text(), nullable=True),
    sa.Column('last_modified', sa.Text(), nullable=True),
    sa.Column('storage_reference', sa.Text(), nullable=True),
    sa.Column('response_size', sa.Integer(), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=False),
    sa.Column('unchanged_from_id', GUID(), nullable=True),
    sa.ForeignKeyConstraint(['crawl_job_id'], ['crawl_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['crawl_url_id'], ['crawl_urls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unchanged_from_id'], ['raw_page_observations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_page_observations_content_hash'), 'raw_page_observations', ['content_hash'], unique=False)
    op.create_index(op.f('ix_raw_page_observations_crawl_job_id'), 'raw_page_observations', ['crawl_job_id'], unique=False)
    op.create_index(op.f('ix_raw_page_observations_crawl_url_id'), 'raw_page_observations', ['crawl_url_id'], unique=False)
    op.create_index(op.f('ix_raw_page_observations_structured_data_hash'), 'raw_page_observations', ['structured_data_hash'], unique=False)
    op.create_table('scraped_product_observations',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('crawl_job_id', GUID(), nullable=False),
    sa.Column('raw_page_id', GUID(), nullable=False),
    sa.Column('source_listing_id', GUID(), nullable=True),
    sa.Column('canonical_product_id', GUID(), nullable=True),
    sa.Column('possible_match_product_id', GUID(), nullable=True),
    sa.Column('product_variant_id', GUID(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_domain', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('locale', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('retailer_product_id', sa.String(length=255), nullable=True),
    sa.Column('normalized_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('identity_hash', sa.String(length=64), nullable=False),
    sa.Column('structured_hash', sa.String(length=64), nullable=False),
    sa.Column('match_status', sa.String(length=50), nullable=False),
    sa.Column('changed_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('adapter_name', sa.String(length=100), nullable=False),
    sa.Column('adapter_version', sa.String(length=50), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("match_status IN ('matched', 'unmatched', 'possible_match', 'conflict')", name='check_scraped_match_status'),
    sa.ForeignKeyConstraint(['canonical_product_id'], ['canonical_products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['crawl_job_id'], ['crawl_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['possible_match_product_id'], ['canonical_products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raw_page_id'], ['raw_page_observations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_listing_id'], ['source_listings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraped_product_observations_canonical_product_id'), 'scraped_product_observations', ['canonical_product_id'], unique=False)
    op.create_index(op.f('ix_scraped_product_observations_crawl_job_id'), 'scraped_product_observations', ['crawl_job_id'], unique=False)
    op.create_index(op.f('ix_scraped_product_observations_identity_hash'), 'scraped_product_observations', ['identity_hash'], unique=False)
    op.create_index(op.f('ix_scraped_product_observations_source_domain'), 'scraped_product_observations', ['source_domain'], unique=False)
    op.create_index(op.f('ix_scraped_product_observations_structured_hash'), 'scraped_product_observations', ['structured_hash'], unique=False)
    op.create_index('uq_crawl_product_observation', 'scraped_product_observations', ['crawl_job_id', 'canonical_url', 'structured_hash'], unique=True)
    op.create_table('crawl_conflicts',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('crawl_job_id', GUID(), nullable=False),
    sa.Column('scraped_product_id', GUID(), nullable=False),
    sa.Column('canonical_product_id', GUID(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('current_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('observed_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reviewed_by_id', GUID(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'rejected')", name='check_crawl_conflict_status'),
    sa.ForeignKeyConstraint(['canonical_product_id'], ['canonical_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['crawl_job_id'], ['crawl_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scraped_product_id'], ['scraped_product_observations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_conflicts_canonical_product_id'), 'crawl_conflicts', ['canonical_product_id'], unique=False)
    op.create_index(op.f('ix_crawl_conflicts_crawl_job_id'), 'crawl_conflicts', ['crawl_job_id'], unique=False)
    op.create_index(op.f('ix_crawl_conflicts_status'), 'crawl_conflicts', ['status'], unique=False)
    op.create_index('uq_pending_crawl_conflict', 'crawl_conflicts', ['scraped_product_id', 'field_name'], unique=True)
    op.create_table('scraped_field_observations',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('scraped_product_id', GUID(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('raw_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('normalized_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('extraction_path', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.String(length=100), nullable=False),
    sa.Column('source_domain', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('adapter_version', sa.String(length=50), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['scraped_product_id'], ['scraped_product_observations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraped_field_observations_scraped_product_id'), 'scraped_field_observations', ['scraped_product_id'], unique=False)
    with op.batch_alter_table('source_listings') as batch:
        batch.add_column(sa.Column('crawl_job_id', GUID(), nullable=True))
        batch.alter_column('import_job_id', existing_type=sa.CHAR(length=36), nullable=True)
        batch.create_foreign_key('fk_source_listings_crawl_job', 'crawl_jobs', ['crawl_job_id'], ['id'], ondelete='CASCADE')
        batch.create_check_constraint(
            'check_source_listing_origin',
            '(import_job_id IS NOT NULL AND crawl_job_id IS NULL) OR '
            '(import_job_id IS NULL AND crawl_job_id IS NOT NULL)',
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM source_listings WHERE crawl_job_id IS NOT NULL")
    with op.batch_alter_table('source_listings') as batch:
        batch.drop_constraint('check_source_listing_origin', type_='check')
        batch.drop_constraint('fk_source_listings_crawl_job', type_='foreignkey')
        batch.alter_column('import_job_id', existing_type=sa.CHAR(length=36), nullable=False)
        batch.drop_column('crawl_job_id')
    op.drop_index(op.f('ix_scraped_field_observations_scraped_product_id'), table_name='scraped_field_observations')
    op.drop_table('scraped_field_observations')
    op.drop_index('uq_pending_crawl_conflict', table_name='crawl_conflicts')
    op.drop_index(op.f('ix_crawl_conflicts_status'), table_name='crawl_conflicts')
    op.drop_index(op.f('ix_crawl_conflicts_crawl_job_id'), table_name='crawl_conflicts')
    op.drop_index(op.f('ix_crawl_conflicts_canonical_product_id'), table_name='crawl_conflicts')
    op.drop_table('crawl_conflicts')
    op.drop_index('uq_crawl_product_observation', table_name='scraped_product_observations')
    op.drop_index(op.f('ix_scraped_product_observations_structured_hash'), table_name='scraped_product_observations')
    op.drop_index(op.f('ix_scraped_product_observations_source_domain'), table_name='scraped_product_observations')
    op.drop_index(op.f('ix_scraped_product_observations_identity_hash'), table_name='scraped_product_observations')
    op.drop_index(op.f('ix_scraped_product_observations_crawl_job_id'), table_name='scraped_product_observations')
    op.drop_index(op.f('ix_scraped_product_observations_canonical_product_id'), table_name='scraped_product_observations')
    op.drop_table('scraped_product_observations')
    op.drop_index(op.f('ix_raw_page_observations_structured_data_hash'), table_name='raw_page_observations')
    op.drop_index(op.f('ix_raw_page_observations_crawl_url_id'), table_name='raw_page_observations')
    op.drop_index(op.f('ix_raw_page_observations_crawl_job_id'), table_name='raw_page_observations')
    op.drop_index(op.f('ix_raw_page_observations_content_hash'), table_name='raw_page_observations')
    op.drop_table('raw_page_observations')
    op.drop_index('uq_crawl_job_normalized_url', table_name='crawl_urls')
    op.drop_index(op.f('ix_crawl_urls_state'), table_name='crawl_urls')
    op.drop_index(op.f('ix_crawl_urls_next_attempt_at'), table_name='crawl_urls')
    op.drop_index(op.f('ix_crawl_urls_crawl_job_id'), table_name='crawl_urls')
    op.drop_index('idx_crawl_frontier_claim', table_name='crawl_urls')
    op.drop_table('crawl_urls')
    op.drop_index(op.f('ix_crawl_jobs_status'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_heartbeat_at'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_domain'), table_name='crawl_jobs')
    op.drop_table('crawl_jobs')
    # ### end Alembic commands ###
