"""initial_schema

Revision ID: 85a02c69bb35
Revises: 
Create Date: 2026-07-13 12:16:25.424816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision: str = '85a02c69bb35'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', app.database.GUID(), nullable=False),
    sa.Column('entity_display_label', sa.String(length=255), nullable=True),
    sa.Column('user_id', app.database.GUID(), nullable=True),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('before_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('after_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('changed_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("action IN ('create', 'update', 'merge', 'approve', 'reject')", name='check_audit_action_type'),
    sa.CheckConstraint("actor_type IN ('user', 'system', 'ai', 'rule')", name='check_audit_actor_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brands',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_normalized_name'), 'brands', ['normalized_name'], unique=True)
    op.create_table('categories',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', app.database.GUID(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_path'), 'categories', ['path'], unique=True)
    op.create_table('ingredient_definitions',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=True),
    sa.Column('aliases', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('function', sa.Text(), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('possible_concerns', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_definitions_normalized_name'), 'ingredient_definitions', ['normalized_name'], unique=True)
    op.create_table('users',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'editor', 'viewer')", name='check_user_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('canonical_products',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('brand_id', app.database.GUID(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('category_id', app.database.GUID(), nullable=True),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('reviewer_id', app.database.GUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("review_status IN ('imported', 'queued', 'enriching', 'enrichment_failed', 'needs_review', 'in_review', 'approved', 'rejected', 'published', 'exported', 'merged')", name='check_product_review_status'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_brand_id_norm_prod_name', 'canonical_products', ['brand_id', 'normalized_name'], unique=False)
    op.create_index(op.f('ix_canonical_products_normalized_name'), 'canonical_products', ['normalized_name'], unique=False)
    op.create_table('import_jobs',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('processed_rows', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('column_mapping', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_by_id', app.database.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'failed', 'cancelled')", name='check_job_status'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_jobs_file_hash'), 'import_jobs', ['file_hash'], unique=False)
    op.create_table('mapping_templates',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('column_mapping', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('transformation_rules', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_by_id', app.database.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('canonical_product_merges',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('source_product_id', app.database.GUID(), nullable=False),
    sa.Column('target_product_id', app.database.GUID(), nullable=False),
    sa.Column('merged_by_id', app.database.GUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merged_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_product_id'], ['canonical_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_product_id'], ['canonical_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_variants',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('canonical_product_id', app.database.GUID(), nullable=False),
    sa.Column('variant_name', sa.String(length=255), nullable=True),
    sa.Column('gtin', sa.String(length=50), nullable=True),
    sa.Column('size', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_product_id'], ['canonical_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_variants_gtin'), 'product_variants', ['gtin'], unique=True)
    op.create_table('source_listings',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('import_job_id', app.database.GUID(), nullable=False),
    sa.Column('canonical_product_id', app.database.GUID(), nullable=True),
    sa.Column('product_variant_id', app.database.GUID(), nullable=True),
    sa.Column('raw_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('retailer', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_product_id'], ['canonical_products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_listings_source_hash'), 'source_listings', ['source_hash'], unique=False)
    op.create_table('formulations',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('canonical_product_id', app.database.GUID(), nullable=False),
    sa.Column('product_variant_id', app.database.GUID(), nullable=True),
    sa.Column('source_listing_id', app.database.GUID(), nullable=True),
    sa.Column('raw_inci_text', sa.Text(), nullable=False),
    sa.Column('market', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_product_id'], ['canonical_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_listing_id'], ['source_listings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formulations_content_hash'), 'formulations', ['content_hash'], unique=False)
    op.create_table('import_job_items',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('import_job_id', app.database.GUID(), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('source_listing_id', app.database.GUID(), nullable=True),
    sa.Column('canonical_product_id', app.database.GUID(), nullable=True),
    sa.Column('product_variant_id', app.database.GUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('match_status', sa.String(length=50), nullable=False),
    sa.Column('duplicate_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('enrichment_status', sa.String(length=50), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_code', sa.String(length=50), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("enrichment_status IN ('not_requested', 'queued', 'processing', 'succeeded', 'validation_failed', 'transient_failed', 'permanent_failed', 'rate_limited', 'configuration_blocked', 'skipped', 'cancelled')", name='check_item_enrichment_status'),
    sa.CheckConstraint("match_status IN ('not_evaluated', 'exact_match', 'deterministic_match', 'candidate', 'ambiguous', 'new_product', 'manually_matched', 'rejected', 'skipped')", name='check_item_match_status'),
    sa.CheckConstraint("status IN ('pending', 'processing', 'awaiting_match_review', 'enriching', 'completed', 'failed', 'skipped', 'cancelled')", name='check_item_status'),
    sa.CheckConstraint('import_job_id IS NOT NULL AND source_row_number IS NOT NULL', name='check_item_row_ref'),
    sa.ForeignKeyConstraint(['canonical_product_id'], ['canonical_products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_listing_id'], ['source_listings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_import_job_row', 'import_job_items', ['import_job_id', 'source_row_number'], unique=True)
    op.create_table('source_prices',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('source_listing_id', app.database.GUID(), nullable=True),
    sa.Column('product_variant_id', app.database.GUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('promotional_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('retailer', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_listing_id'], ['source_listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrichment_runs',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('import_job_id', app.database.GUID(), nullable=True),
    sa.Column('import_job_item_id', app.database.GUID(), nullable=True),
    sa.Column('source_listing_id', app.database.GUID(), nullable=True),
    sa.Column('canonical_product_id', app.database.GUID(), nullable=True),
    sa.Column('product_variant_id', app.database.GUID(), nullable=True),
    sa.Column('parent_enrichment_run_id', app.database.GUID(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('schema_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('requested_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('retry_reason', sa.Text(), nullable=True),
    sa.Column('input_content_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('validation_errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('success', 'failed')", name='check_enrichment_status'),
    sa.ForeignKeyConstraint(['canonical_product_id'], ['canonical_products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_job_item_id'], ['import_job_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_enrichment_run_id'], ['enrichment_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_listing_id'], ['source_listings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrichment_runs_input_content_hash'), 'enrichment_runs', ['input_content_hash'], unique=False)
    op.create_index(op.f('ix_enrichment_runs_status'), 'enrichment_runs', ['status'], unique=False)
    op.create_table('formulation_ingredients',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('formulation_id', app.database.GUID(), nullable=False),
    sa.Column('ingredient_definition_id', app.database.GUID(), nullable=True),
    sa.Column('raw_inci_name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_key_ingredient', sa.Boolean(), nullable=False),
    sa.Column('evidence_source', sa.String(length=255), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('confidence_score <= 1.0', name='check_ingredient_confidence_max'),
    sa.CheckConstraint('confidence_score >= 0.0', name='check_ingredient_confidence_min'),
    sa.ForeignKeyConstraint(['formulation_id'], ['formulations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_definition_id'], ['ingredient_definitions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_formulation_position', 'formulation_ingredients', ['formulation_id', 'position'], unique=True)
    op.create_table('field_values',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('canonical_product_id', app.database.GUID(), nullable=True),
    sa.Column('product_variant_id', app.database.GUID(), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('reviewer_id', app.database.GUID(), nullable=True),
    sa.Column('enrichment_run_id', app.database.GUID(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("review_status IN ('confirmed', 'inferred', 'unknown', 'conflicting', 'not_applicable')", name='check_field_review_status'),
    sa.CheckConstraint("source_type IN ('source_data', 'deterministic_rule', 'ai_inference', 'human_edit')", name='check_field_source_type'),
    sa.CheckConstraint('(canonical_product_id IS NOT NULL AND product_variant_id IS NULL) OR (canonical_product_id IS NULL AND product_variant_id IS NOT NULL)', name='check_field_value_entity_ref'),
    sa.CheckConstraint('confidence_score <= 1.0', name='check_field_confidence_max'),
    sa.CheckConstraint('confidence_score >= 0.0', name='check_field_confidence_min'),
    sa.ForeignKeyConstraint(['canonical_product_id'], ['canonical_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enrichment_run_id'], ['enrichment_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_field_values_name_current', 'field_values', ['field_name', 'is_current'], unique=False)
    op.create_index('uq_current_val_product', 'field_values', ['canonical_product_id', 'field_name'], unique=True, sqlite_where=sa.text('is_current = 1 AND canonical_product_id IS NOT NULL'), postgresql_where=sa.text('is_current = True AND canonical_product_id IS NOT NULL'))
    op.create_index('uq_current_val_variant', 'field_values', ['product_variant_id', 'field_name'], unique=True, sqlite_where=sa.text('is_current = 1 AND product_variant_id IS NOT NULL'), postgresql_where=sa.text('is_current = True AND product_variant_id IS NOT NULL'))
    op.create_table('validation_issues',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('import_job_id', app.database.GUID(), nullable=True),
    sa.Column('import_job_item_id', app.database.GUID(), nullable=True),
    sa.Column('source_listing_id', app.database.GUID(), nullable=True),
    sa.Column('canonical_product_id', app.database.GUID(), nullable=True),
    sa.Column('product_variant_id', app.database.GUID(), nullable=True),
    sa.Column('formulation_id', app.database.GUID(), nullable=True),
    sa.Column('field_value_id', app.database.GUID(), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('issue_type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by_id', app.database.GUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_by_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("created_by_type IN ('system', 'rule', 'ai', 'user')", name='check_issue_creator_type'),
    sa.CheckConstraint("severity IN ('informational', 'warning', 'blocking')", name='check_issue_severity'),
    sa.CheckConstraint('(import_job_id IS NOT NULL AND import_job_item_id IS NULL AND source_listing_id IS NULL AND canonical_product_id IS NULL AND product_variant_id IS NULL AND formulation_id IS NULL AND field_value_id IS NULL) OR (import_job_id IS NULL AND import_job_item_id IS NOT NULL AND source_listing_id IS NULL AND canonical_product_id IS NULL AND product_variant_id IS NULL AND formulation_id IS NULL AND field_value_id IS NULL) OR (import_job_id IS NULL AND import_job_item_id IS NULL AND source_listing_id IS NOT NULL AND canonical_product_id IS NULL AND product_variant_id IS NULL AND formulation_id IS NULL AND field_value_id IS NULL) OR (import_job_id IS NULL AND import_job_item_id IS NULL AND source_listing_id IS NULL AND canonical_product_id IS NOT NULL AND product_variant_id IS NULL AND formulation_id IS NULL AND field_value_id IS NULL) OR (import_job_id IS NULL AND import_job_item_id IS NULL AND source_listing_id IS NULL AND canonical_product_id IS NULL AND product_variant_id IS NOT NULL AND formulation_id IS NULL AND field_value_id IS NULL) OR (import_job_id IS NULL AND import_job_item_id IS NULL AND source_listing_id IS NULL AND canonical_product_id IS NULL AND product_variant_id IS NULL AND formulation_id IS NOT NULL AND field_value_id IS NULL) OR (import_job_id IS NULL AND import_job_item_id IS NULL AND source_listing_id IS NULL AND canonical_product_id IS NULL AND product_variant_id IS NULL AND formulation_id IS NULL AND field_value_id IS NOT NULL)', name='check_validation_issue_single_target'),
    sa.ForeignKeyConstraint(['canonical_product_id'], ['canonical_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_value_id'], ['field_values.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['formulation_id'], ['formulations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['import_job_item_id'], ['import_job_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_listing_id'], ['source_listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_validation_issues_unresolved', 'validation_issues', ['canonical_product_id'], unique=False, postgresql_where=sa.text('resolved = False'), sqlite_where=sa.text('resolved = 0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_validation_issues_unresolved', table_name='validation_issues', postgresql_where=sa.text('resolved = False'), sqlite_where=sa.text('resolved = 0'))
    op.drop_table('validation_issues')
    op.drop_index('uq_current_val_variant', table_name='field_values', sqlite_where=sa.text('is_current = 1 AND product_variant_id IS NOT NULL'), postgresql_where=sa.text('is_current = True AND product_variant_id IS NOT NULL'))
    op.drop_index('uq_current_val_product', table_name='field_values', sqlite_where=sa.text('is_current = 1 AND canonical_product_id IS NOT NULL'), postgresql_where=sa.text('is_current = True AND canonical_product_id IS NOT NULL'))
    op.drop_index('idx_field_values_name_current', table_name='field_values')
    op.drop_table('field_values')
    op.drop_index('uq_formulation_position', table_name='formulation_ingredients')
    op.drop_table('formulation_ingredients')
    op.drop_index(op.f('ix_enrichment_runs_status'), table_name='enrichment_runs')
    op.drop_index(op.f('ix_enrichment_runs_input_content_hash'), table_name='enrichment_runs')
    op.drop_table('enrichment_runs')
    op.drop_table('source_prices')
    op.drop_index('idx_import_job_row', table_name='import_job_items')
    op.drop_table('import_job_items')
    op.drop_index(op.f('ix_formulations_content_hash'), table_name='formulations')
    op.drop_table('formulations')
    op.drop_index(op.f('ix_source_listings_source_hash'), table_name='source_listings')
    op.drop_table('source_listings')
    op.drop_index(op.f('ix_product_variants_gtin'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_table('canonical_product_merges')
    op.drop_table('mapping_templates')
    op.drop_index(op.f('ix_import_jobs_file_hash'), table_name='import_jobs')
    op.drop_table('import_jobs')
    op.drop_index(op.f('ix_canonical_products_normalized_name'), table_name='canonical_products')
    op.drop_index('idx_brand_id_norm_prod_name', table_name='canonical_products')
    op.drop_table('canonical_products')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ingredient_definitions_normalized_name'), table_name='ingredient_definitions')
    op.drop_table('ingredient_definitions')
    op.drop_index(op.f('ix_categories_path'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_brands_normalized_name'), table_name='brands')
    op.drop_table('brands')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
